// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementSystem.Infrastructure.Contexts;

namespace TaskManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(TasksContext))]
    partial class TasksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskManagementSystem.Infrastructure.Entities.ManagedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ActualCompletionHours");

                    b.Property<DateTime?>("DateOfCompletion");

                    b.Property<DateTime>("DateOfIssue");

                    b.Property<string>("Description");

                    b.Property<string>("Executors");

                    b.Property<string>("Name");

                    b.Property<Guid?>("ParentTaskId");

                    b.Property<long>("PlannedCompletionHours");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.ToTable("ManagedTask");
                });

            modelBuilder.Entity("TaskManagementSystem.Infrastructure.Entities.ManagedTask", b =>
                {
                    b.HasOne("TaskManagementSystem.Infrastructure.Entities.ManagedTask", "ParentTask")
                        .WithMany("SubTasks")
                        .HasForeignKey("ParentTaskId");
                });
#pragma warning restore 612, 618
        }
    }
}
